#pragma once
#ifndef __SOY_KNIFE_ANIMATION_STATE__
#define __SOY_KNIFE_ANIMATION_STATE__

enum SoyKnifeAnimationState
{
	SOY_KNIFE_IDLE_RIGHT,
	SOY_KNIFE_IDLE_LEFT,
	SOY_KNIFE_ATTACK_RIGHT,
	SOY_KNIFE_ATTACK_LEFT,
	//NUM_OF_ANIMATION_STATES
};

#endif /* defined (__SOY_KNIFE_ANIMATION_STATE__)*/