#pragma once
#ifndef __WINCHESTER_SHOTGUN_ANIMATION_STATE__
#define __WINCHESTER_SHOTGUN_ANIMATION_STATE__

enum WinchesterShotgunAnimationState
{
	WINCHESTER_SHOTGUN_IDLE_RIGHT,
	WINCHESTER_SHOTGUN_IDLE_LEFT,
	WINCHESTER_SHOTGUN_ATTACK_RIGHT,
	WINCHESTER_SHOTGUN_ATTACK_LEFT,
	//NUM_OF_ANIMATION_STATES
};

#endif /* defined (__WINCHESTER_SHOTGUN_ANIMATION_STATE__)*/